title: Wei's technical notes
heading: Wei
sub_heading: Learn cutting-edge technologies with me
author: Wei Wang
description: Learn cutting-edge technologies with me
excerpt_separator: <!--more-->

permalink: /:categories/:title/

# social links
twitter_username: givemepower8
github_username:  givemepower8

show_excerpts: true # set to false to remove excerpts on the homepage

sass:
  sass_dir: _sass
  style: compact