title: Wei's technical notes
author: Wei Wang
description: Learn cutting-edge technologies with me
logo: /assets/img/Wei_Emoji.gif
excerpt_separator: <!--more-->

# social links
twitter_username: givemepower8
github_username:  givemepower8

show_excerpts: true # set to false to remove excerpts on the homepage

sass:
  sass_dir: _sass
  style: compact